### ISSUE TITLE
Find a BUG

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/BSkyBlock#125]
[20:30:34] [Server thread/INFO]: BackWheel fell from a high place
[20:30:42] [Server thread/INFO]: BackWheel issued server command: /is
[20:30:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is' in world.bentobox.bskyblock.commands.IslandCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:896) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:889) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:806) [spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at world.bentobox.bentobox.managers.IslandWorldManager.getIslandXOffset(IslandWorldManager.java:265) ~[?:?]
        at world.bentobox.bentobox.managers.island.NewIsland.getNextIsland(NewIsland.java:244) ~[?:?]
        at world.bentobox.bentobox.managers.island.NewIsland.newIsland(NewIsland.java:140) ~[?:?]
        at world.bentobox.bentobox.managers.island.NewIsland.<init>(NewIsland.java:54) ~[?:?]
        at world.bentobox.bentobox.managers.island.NewIsland.<init>(NewIsland.java:29) ~[?:?]
        at world.bentobox.bentobox.managers.island.NewIsland$Builder.build(NewIsland.java:128) ~[?:?]
        at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.execute(IslandCreateCommand.java:77) ~[?:?]
        at world.bentobox.bskyblock.commands.IslandCommand.lambda$execute$1(IslandCommand.java:79) ~[?:?]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_211]
        at world.bentobox.bskyblock.commands.IslandCommand.execute(IslandCommand.java:79) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:251) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-1eece4f-84400e6]
        ... 16 more

**Comment by Poslovitch** [comment]
`/bbox v` and server information please...

**Comment by Pau1am** [comment]
[20:53:02] [Server thread/INFO]: Running SPIGOT 1.14.
[20:53:02] [Server thread/INFO]: Bentobox 版本：1.5.0-SNAPSHOT
[20:53:02] [Server thread/INFO]: 已加载游戏世界：
[20:53:02] [Server thread/INFO]: 已加载组件
[20:53:02] [Server thread/INFO]: Biomes 0.4.5-SNAPSHOT-#28
[20:53:02] [Server thread/INFO]: BSkyBlock 1.5.0
[20:53:02] [Server thread/INFO]: Challenges 0.7.0-SNAPSHOT-#164
[20:53:02] [Server thread/INFO]: Level 1.4.0
[20:53:02] [Server thread/INFO]: Limits 0.2.0-SNAPSHOT
>ver
[20:53:08] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1eece4f-84400e6 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
[20:53:08] [Server thread/INFO]: Checking version, please wait...
[20:53:09] [Thread-16/INFO]: You are 14 version(s) behind

**Comment by Poslovitch** [comment]
Thanks. Moving to appropriate repository.
