### ISSUE TITLE
Island Creation Bugs and Slimefun compatibility issues.

### ISSUE THREAD

**Issue by EnderBro123** [BentoBoxWorld/BSkyBlock#149]
**Description**

Island Blueprints are very buggy and do not work properly. The normal island simply says that it can't find a safe spot to teleport me to. 

**Steps to reproduce the behavior:**
There really is none, since this is on a fresh install. I also tried editing the blueprints via /bbox manage, but I simply made it worse, and even after deleting the blueprints folder and restarting to regenerate the folder with the files inside, the same "Normal Islanand wont tp me to it" issue occurs again.

**Expected behavior**

The plugin not glitching (and causing me a complete nightmare).

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []

Not using one. The plugin says it's connected to something, but I have NO idea what.

I'm using BiscuitHosting. I have no clue on how to get this info.

 - Java Version: [e.g. Java 8]
I'm using BiscuitHosting. I have no clue on how to get this info.

 - BentoBox version: [e.g. 1.7.2.21]
Latest version.

 - Addons installed? [Do '/bentobox version' and copy/paste from the console]

 - Other plugins? [Do '/plugins' and copy/paste from the console]

![2019-06-26_14 49 33](https://user-images.githubusercontent.com/51277766/60217476-a587e480-9821-11e9-9b4a-37aeacef320a.png)

I also wanted to mention, even though this should go to BentoBox, that it can't be used with Slimefun due to certain machines from it such as an Ore Crusher, can't be interacted with, due to fences.

**Comment by tastybento** [comment]
Very important: do **/bbox version** and paste the full result you see from the console. I need to replicate your setup otherwise I can't even start to investigate.

**Comment by tastybento** [comment]
SlimeFun issue is being tracked here: https://github.com/BentoBoxWorld/BentoBox/issues/773

**Comment by MagmaSlime123** [comment]
> Very important: do **/bbox version** and paste the full result you see from the console. I need to replicate your setup otherwise I can't even start to investigate.

Sorry about the late reply.

![2019-06-26_21 55 56](https://user-images.githubusercontent.com/51277766/60235608-329c5f00-985d-11e9-8519-2e69168994ab.png)

Bbox version simply poops out an error, but it does list my server's software version and BentoBox's version. Setting a island home also wont work since it says you need to be on the island to do so, but I already am.

**Comment by tastybento** [comment]
Is this a clean install? Did you edit any of the config files.

I need to see the console log with the errors - they'll pop up when it says internal error. It's best if you zip it up and drag and drop it into this ticket. Also, best if you share the log from when the server starts. You can find it in the logs folder (latest).

**Comment by MagmaSlime123** [comment]
> Is this a clean install? Did you edit any of the config files.
> 
> I need to see the console log with the errors - they'll pop up when it says internal error. It's best if you zip it up and drag and drop it into this ticket. Also, best if you share the log from when the server starts. You can find it in the logs folder (latest).

Only thing I edited was making the plugin not turn the nether and the end into islands.

And, this is the error. It's quite small, so I didn't pastebin it.

```
27.06 11:24:46 [Server] ERROR null
27.06 11:24:46 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'bbox version' in world.bentobox.bentobox.commands.BentoBoxCommand(bentobox)
27.06 11:24:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
27.06 11:24:46 [Server] INFO Caused by: java.lang.NullPointerException
27.06 11:24:46 [Server] INFO at world.bentobox.bentobox.managers.IslandWorldManager.isEndGenerate(IslandWorldManager.java:324) ~[?:?]
27.06 11:24:46 [Server] INFO at world.bentobox.bentobox.commands.BentoBoxVersionCommand.lambda$execute$0(BentoBoxVersionCommand.java:72) ~[?:?]
27.06 11:24:46 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
27.06 11:24:46 [Server] INFO at world.bentobox.bentobox.commands.BentoBoxVersionCommand.execute(BentoBoxVersionCommand.java:51) ~[?:?]
27.06 11:24:46 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
27.06 11:24:46 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
27.06 11:24:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-631]
27.06 11:24:46 [Server] INFO ... 14 more
```

But yeah. Only issues I'm having is the glitched island issues, /bbox version not working, slimefun compatibility, and /is sethome not working.

**Comment by tastybento** [comment]
That error indicates that the game mode world settings have not been loaded properly. Can you start the server and then share the console log from the very start until it says BENTOBOX? I suspect there's an error there that will help explain what's going on.

**Comment by tastybento** [comment]
One more thing - which version of BSkyBlock are you using?

**Comment by MagmaSlime123** [comment]
> One more thing - which version of BSkyBlock are you using?

The latest version. I'm not sure if new versions came out at all, but I really think a dedicated BSkyBlock Discord would be nice. Also, I'm not really getting any errors at all, only error s the bbox version thing.

**Comment by Poslovitch** [comment]
> I really think a dedicated BSkyBlock Discord would be nice

https://discord.bentobox.world

**Comment by MagmaSlime123** [comment]
> > I really think a dedicated BSkyBlock Discord would be nice
> 
> https://discord.bentobox.world

Nevermind. Anyways, can the other issues be fixed? I tried to output as much info as possible but the console wont give anything but 1 error about /bbox version.

**Comment by tastybento** [comment]
Okay, I need a copy of your BentoBox folder. Zip it up and drop it in the box here or put it somewhere so I can download it. I'll need that to be able to debug this and see if I can get the same issues you see.

**Comment by MagmaSlime123** [comment]
> Okay, I need a copy of your BentoBox folder. Zip it up and drop it in the box here or put it somewhere so I can download it. I'll need that to be able to debug this and see if I can get the same issues you see.

[BentoBoxUsingForGitHubIssue.zip](https://github.com/BentoBoxWorld/BSkyBlock/files/3340987/BentoBoxUsingForGitHubIssue.zip)

Also, @Poslovitch is also working on another issue I reported about relating to BSkyBlock Settings not working with Slimefun, but I decided to keep these 2 sepreated so this doesn't get all messy. :P

**Comment by tastybento** [comment]
I found a few issues:

* Caveblock has fix super flat active which will cause an infinite loop. 
* There's a number of old data in the database. Looks like it may not have been deleted between game resets.

I'm adding code to try and avoid bugging out, but here's some thing you should do: 

1. Stop the server and edit the CaveBlock config.yml and change the CLEAN_SUPER_FLAT: true to CLEAN_SUPER_FLAT: false. It's on line 197. Do not turn it on in the settings.
2. Decide if you really want to keep the current world/database or just delete it all and start from scratch. If you do this, delete the BentoBox database folder as well and the worlds.
3. If you don't reset everything, use the latest snapshot release that'll come out after I commit the fixes. You'll see the comment in this ticket when that happens.

Also, a minor comment, but you've set the island protection range to 1000. That means each island will be 2000x2000 blocks big. That's okay, but those are some really big islands and it will mean that a lot of blocks have to be deleted or calculated etc. per island. I'd recommend keeping the island sizes low. But it's up to you.
