### ISSUE TITLE
"Loading terrain" screen when going through nether portal for first time

### ISSUE THREAD

**Issue by LordSheep** [BentoBoxWorld/BSkyBlock#162]
**Description**
When stepping into the nether portal for the first time sometimes there will be a "Loading terrain..." screen and also an error in the console.  
(This happens in double and harder islands more often than in default island)
(And you have to close Minecraft and reopen it to be able to fix it)

**Steps to reproduce the behavior:**
(I had a backup of server files where no one had logged onto the server and no islands were created yet and I pasted schematics into those files)
1. Edit and save new schematic for every island (island, double, harder, nether-island, end-island)
2. Add them to /bentobox manage
3. Restart the server or don't (same outcome either way)
4. Create an island and build a nether portal.
5. Go through nether portal.
6. See "Loading terrain..."

**Expected behavior**
Go through to the nether. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30538383/61900845-7631c980-aeec-11e9-8ad3-af6285baf561.png)

**Server Information:**

[Please complete the following information:]
 - Database being used: JSON
 - OS: No clue
 - Java Version: No clue
 - BentoBox version: 1.5.3
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
![image](https://user-images.githubusercontent.com/30538383/61901091-ff490080-aeec-11e9-86e2-755edf970366.png)

 - Other plugins? [Do '/plugins' and copy/paste from the console]
![image](https://user-images.githubusercontent.com/30538383/61901126-125bd080-aeed-11e9-84ef-bf4a231df66d.png)

**Additional context**
**Console message:** (The messages are all look to be the same/similar except for the task number is different each time)
```
25.07 14:49:28 [Server] Server thread/WARN [BentoBox] Task #72 for BentoBox v1.5.3 generated an exception
25.07 14:49:28 [Server] INFO java.util.ConcurrentModificationException: null
25.07 14:49:28 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
25.07 14:49:28 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_191]
25.07 14:49:28 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_191]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:204) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:144) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:91) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:105) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.setLocation(Entity.java:1272) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1105) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.teleport(PlayerConnection.java:1071) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:662) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:658) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:451) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at world.bentobox.bentobox.util.teleport.SafeSpotTeleport.lambda$teleportEntity$4(SafeSpotTeleport.java:249) ~[?:?]
25.07 14:49:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-df0eb25-30a6337]
25.07 14:49:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by tastybento** [comment]
This appears to be a bug with the server software itself. I recommend upgrading to the latest 1.14.4 build if you haven't already.
