### ISSUE TITLE
my server starts to fall...

### ISSUE THREAD

**Issue by SliderKP** [BentoBoxWorld/BSkyBlock#194]
i getting this command when i use commands about bSkyblock.
```
[23:33:09 INFO]: SliderKP issued server command: /is
[23:33:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is' in world.bentobox.bskyblock.commands.IslandCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[overcraft.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[overcraft.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[overcraft.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
        at world.bentobox.bentobox.managers.IslandWorldManager.getMaxIslands(IslandWorldManager.java:296) ~[?:?]
        at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.canExecute(IslandCreateCommand.java:44) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bskyblock.commands.IslandCommand.lambda$execute$1(IslandCommand.java:79) ~[?:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_222]
        at world.bentobox.bskyblock.commands.IslandCommand.execute(IslandCommand.java:79) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[overcraft.jar:git-Paper-624]
        ... 14 more

```
no changes, one day bSkyblock decide stop working.

**Comment by tastybento** [comment]
I see no server or version info in your report. I can't help you sorry. Read the instructions when you click the Bug button:

### Description
#### Describe the bug




#### Steps to reproduce the behavior




#### Screenshots and videos



#### Expected behavior



### Environment

#### Server


 - OS: **________**
 - Java version: **________**

#### Plugins


```
_______
```

#### BentoBox setup

##### BentoBox and Addons


```
_______
```

##### Configuration


 - Database: **________** 

### Additional context

**Comment by tastybento** [comment]
At least do **/bbox version** and share what is says. Also, something must have changed...
