### ISSUE TITLE
bSkyblock stop working

### ISSUE THREAD

**Issue by SliderKP** [BentoBoxWorld/BSkyBlock#195]
#### Describe the bug

bSkyblock stop working

#### Steps to reproduce the behavior

use commands about bSkyblock, example:
[23:33:09 INFO]: SliderKP issued server command: /is
[23:33:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is' in world.bentobox.bskyblock.commands.IslandCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[overcraft.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[overcraft.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[overcraft.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[overcraft.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
        at world.bentobox.bentobox.managers.IslandWorldManager.getMaxIslands(IslandWorldManager.java:296) ~[?:?]
        at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.canExecute(IslandCreateCommand.java:44) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bskyblock.commands.IslandCommand.lambda$execute$1(IslandCommand.java:79) ~[?:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_222]
        at world.bentobox.bskyblock.commands.IslandCommand.execute(IslandCommand.java:79) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[overcraft.jar:git-Paper-624]
        ... 14 more

#### Expected behavior

just a day stop working, and i try to update and continue without working.
#### Server

 - OS: CentOS 7.5
 - Java version: 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

#### Plugins

```
> pl
[01:05:33 INFO]: Plugins (39): AccountGuard*, AdvancedReporter*, AuctionHouse, AutoShutdown*, BentoBox, BossMessenger*, ChatControl*, ChestCommands*, Citizens, ClearLag*, CombatLogX, CommandNPC*, CPCameraStudioReborn*, EasyBackup*, EasyBackupCore*, Essentials*, EssentialsChat*, EssentialsSpawn*, FastAsyncWorldEdit, HolographicDisplays, LiteBans, LuckPerms, Multiverse-Core*, MVdWPlaceholderAPI*, MyCommand, PlaceholderAPI*, PlugMan*, ProtocolLib*, ProtocolSupport, ProtocolSupportLegacyChest, ShopGUIPlus*, StackMob, TAB, UltimateStacker, UUIDSpoof-Fix*, Vault, VotingPlugin*, WorldEdit, WorldGuard

```

##### BentoBox and Addons

```
[01:07:45 INFO]: Corriendo PAPER 1.13.2.
[01:07:45 INFO]: BentoBox version: 1.6.0-SNAPSHOT-b1231
[01:07:45 INFO]: Mundos de juego cargados:
[01:07:45 INFO]: Addons cargados:
[01:07:45 INFO]: BSkyBlock 1.6.0 (INCOMPATIBLE)
```

##### Configuration

 - Database: **YAML**

**Comment by BONNe** [comment]
You are using BentoBox 1.6 snapshot.
Update to release version!!

**Comment by Poslovitch** [comment]
> BSkyBlock 1.6.0 (INCOMPATIBLE)

**Comment by SliderKP** [comment]
> > BSkyBlock 1.6.0 (INCOMPATIBLE)

why incompatible?



> You are using BentoBox 1.6 snapshot.
> Update to release version!!

> bentobox version
[21:09:23 INFO]: Corriendo PAPER 1.13.2.
[21:09:23 INFO]: BentoBox version: 1.6.0-SNAPSHOT-b1231
[21:09:23 INFO]: Mundos de juego cargados:
[21:09:23 INFO]: Addons cargados:
[21:09:23 INFO]: BSkyBlock 1.7.0-SNAPSHOT-b442 (INCOMPATIBLE)

**Comment by BONNe** [comment]
You cannot mix versions.
If you use BentoBox 1.6.0 then you need to use bSkyBlock 1.6.0
And if you use BSkyBlock 1.7.0 snapshot, also bentobox should be on the same snapshot.

In the first report, you show that 

```
[01:07:45 INFO]: BentoBox version: **1.6.0-SNAPSHOT-b1231**
[01:07:45 INFO]: BSkyBlock **1.6.0** (INCOMPATIBLE)
```

The issue here is that you are using SNAPSHOT build of BentoBox and release version of BSkyBlock.

**IT WILL NOT RUN IF YOU USE SNAPSHOT WITH RELEASE**

**Comment by SliderKP** [comment]
> You cannot mix versions.
> If you use BentoBox 1.6.0 then you need to use bSkyBlock 1.6.0
> And if you use BSkyBlock 1.7.0 snapshot, also bentobox should be on the same snapshot.
> 
> In the first report, you show that
> 
> ```
> [01:07:45 INFO]: BentoBox version: **1.6.0-SNAPSHOT-b1231**
> [01:07:45 INFO]: BSkyBlock **1.6.0** (INCOMPATIBLE)
> ```
> 
> The issue here is that you are using SNAPSHOT build of BentoBox and release version of BSkyBlock.
> 
> **IT WILL NOT RUN IF YOU USE SNAPSHOT WITH RELEASE**

where i can download the correct bentobox? i dont found 1.7.0 release.
