### ISSUE TITLE
Server Crash when user tries to create island

### ISSUE THREAD

**Issue by alfdef1** [BentoBoxWorld/BSkyBlock#220]
[17:00:55] [Paper Watchdog Thread/ERROR]: The server has not responded for 55 seconds! Creating thread dump
[17:00:55] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:00:55] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:00:55] [Paper Watchdog Thread/ERROR]: The server is waiting on these chunks: [[( -226,-313) in 'ASkyBlock']]
[17:00:55] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:00:55] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:00:55] [Paper Watchdog Thread/ERROR]: 	PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
[17:00:55] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:00:55] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.bi(IAsyncTaskHandler.java:131)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:285)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:373)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:80)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:334)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.World.getType(World.java:726)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getNMS(CraftBlock.java:69)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.isEmpty(CraftBlock.java:590)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.isIsland(DefaultNewIslandLocationStrategy.java:106)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.getNextLocation(DefaultNewIslandLocationStrategy.java:53)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.island.NewIsland.newIsland(NewIsland.java:169)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.island.NewIsland.<init>(NewIsland.java:52)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.island.NewIsland$Builder.build(NewIsland.java:142)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.api.commands.island.IslandResetCommand.resetIsland(IslandResetCommand.java:138)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.api.commands.island.IslandResetCommand.execute(IslandResetCommand.java:92)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.panels.IslandCreationPanel.lambda$openPanel$1(IslandCreationPanel.java:53)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.panels.IslandCreationPanel$$Lambda$6480/1205077613.onClick(Unknown Source)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:55)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.listeners.PanelListenerManager$$Lambda$6481/1197831740.accept(Unknown Source)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		java.util.Optional.ifPresent(Optional.java:159)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:53)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor748.execute(Unknown Source)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor$$Lambda$3093/265706025.execute(Unknown Source)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$5658/541522132.run(Unknown Source)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[17:00:55] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)

**Comment by tastybento** [comment]
Weird. It looks like the server just couldn't load the chunk at blocks -3616,-5008 to -3601,-4993. Could you go to say -3605, 120, -5000 and see what is there?

I need more information. Start server, issue command `bbox version` in console and copy and paste the result here. It'll look something like:
```
> bbox version
[08:41:15 INFO]: Running PAPER 1.14.4.
[08:41:15 INFO]: BentoBox version: 1.9.0-SNAPSHOT-LOCAL
[08:41:15 INFO]: Database: JSON
[08:41:15 INFO]: Loaded Game Worlds:
[08:41:15 INFO]: acidisland_world (AcidIsland): Overworld, Nether, End
[08:41:15 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
[08:41:15 INFO]: Loaded Addons:
[08:41:15 INFO]: AcidIsland 1.9.0-SNAPSHOT-LOCAL (ENABLED)
[08:41:15 INFO]: BSkyBlock 1.9.0-SNAPSHOT-LOCAL (ENABLED)
[08:41:15 INFO]: Greenhouses 0.4.5-SNAPSHOT (ENABLED)
[08:41:15 INFO]: Level 1.9.0-SNAPSHOT-LOCAL (ENABLED)
[08:41:15 INFO]: Likes 1.7.0-SNAPSHOT-LOCAL (ENABLED)
[08:41:15 INFO]: Limits 1.9.0-SNAPSHOT-LOCAL (ENABLED)
[08:41:15 INFO]: Warps 1.8.1 (ENABLED)
```
Also, what build of Paper are you using?

**Comment by alfdef1** [comment]
Thanks for the quick response!

/bbox version

[17:48:42 INFO]: Running PAPER 1.14.4.
[17:48:42 INFO]: BentoBox version: 1.8.0
[17:48:42 INFO]: Database: JSON
[17:48:42 INFO]: Loaded Game Worlds:
[17:48:42 INFO]: ASkyBlock (ASkyBlock): Overworld, Nether, End
[17:48:42 INFO]: Loaded Addons:
[17:48:42 INFO]: BSkyBlock 1.8.0 (ENABLED)
[17:48:42 INFO]: Challenges 0.8.0-1.6.0 (ENABLED)
[17:48:42 INFO]: Warps 1.8.2 (ENABLED)

At the position is an Island not assigned to anybody.
![image](https://user-images.githubusercontent.com/10639428/69822797-885ba580-1207-11ea-9073-3cfa9dd81983.png)

**Comment by tastybento** [comment]
Okay. Edit spigot.yml and change `timeout-time:` to something large, like 60000.
Once everything is working, it should be okay to put it back. Stop the server, then start it again and then do an island reset or make a new island. It will take a while to do this, so just wait.

What is happening is that you have a world with a lot of islands in it already that BentoBox doesn't know about. When you reset your island, it tried to find a clear spot but could not in time because of all the islands. Once you do this once, the database will have all the empty islands in it, and new island generation will be faster.

**Comment by tastybento** [comment]
In the meantime, I am going to look at making this part of the game async so it never crashes.

**Comment by alfdef1** [comment]
Seems that it's the same behavior when creating a new island for the second time but after the third time it seems to work fine.

**Comment by tastybento** [comment]
Okay. Can you run this command and tell me what it says?
 `bsb purge unowned`

Don't run it twice because it'll delete the unowned islands. I'm just interested how many you have.

**Comment by alfdef1** [comment]
`
[20:28:51 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_14_R1.TileEntityChest@147705ba) at 5234,142,6033 (Block{minecraft:air}) where there was no entity tile!
[20:28:51 WARN]: Chunk coordinates: 5232,6032
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.setTileEntity(Chunk.java:574)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.a(Chunk.java:545)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.a(Chunk.java:973)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.a(Chunk.java:523)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.World.getTileEntity(World.java:1120)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.getTileEntity(WorldServer.java:211)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.BlockChest.remove(BlockChest.java:183)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.IBlockData.remove(IBlockData.java:202)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.setType(Chunk.java:346)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.World.setTypeAndData(World.java:420)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:196)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.setBlockData(CraftBlock.java:178)
[20:28:51 WARN]:        at world.bentobox.bentobox.util.DeleteIslandChunks.regenerateChunk(DeleteIslandChunks.java:91)
[20:28:51 WARN]:        at world.bentobox.bentobox.util.DeleteIslandChunks.lambda$null$0(DeleteIslandChunks.java:51)
[20:28:51 WARN]:        at java.util.Optional.ifPresent(Optional.java:159)
[20:28:51 WARN]:        at world.bentobox.bentobox.util.DeleteIslandChunks.lambda$new$1(DeleteIslandChunks.java:46)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[20:28:51 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:28:51 INFO]: Removing corrupt tile entity
[20:28:51 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_14_R1.TileEntityChest@147705ba) at 5234,142,6033 (Block{minecraft:air}) where there was no entity tile!
[20:28:51 WARN]: Chunk coordinates: 5232,6032
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.setTileEntity(Chunk.java:574)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.World.setTileEntity(World.java:1171)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.a(Chunk.java:547)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.a(Chunk.java:973)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.a(Chunk.java:523)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.World.getTileEntity(World.java:1120)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.getTileEntity(WorldServer.java:211)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.BlockChest.remove(BlockChest.java:183)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.IBlockData.remove(IBlockData.java:202)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.Chunk.setType(Chunk.java:346)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.World.setTypeAndData(World.java:420)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:196)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.setBlockData(CraftBlock.java:178)
[20:28:51 WARN]:        at world.bentobox.bentobox.util.DeleteIslandChunks.regenerateChunk(DeleteIslandChunks.java:91)
[20:28:51 WARN]:        at world.bentobox.bentobox.util.DeleteIslandChunks.lambda$null$0(DeleteIslandChunks.java:51)
[20:28:51 WARN]:        at java.util.Optional.ifPresent(Optional.java:159)
[20:28:51 WARN]:        at world.bentobox.bentobox.util.DeleteIslandChunks.lambda$new$1(DeleteIslandChunks.java:46)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[20:28:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[20:28:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[20:28:51 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:28:51 INFO]: Removing corrupt tile entity
`

**Comment by tastybento** [comment]
I did said don't run it twice... did you? it's now trying to delete all the unowned islands if you did.

**Comment by alfdef1** [comment]
Sorry for the late response I wasn't at home.
Running the command twice wasn't an issue it seems to stop deleting after a while.
The issue with hanging/crash when a user creates a new island still occurs.

**Comment by tastybento** [comment]
Please post the console log from this now so I can look at it.

**Comment by alfdef1** [comment]
You can find the log here: https://hastebin.com/emabipikef.sql

**Comment by tastybento** [comment]
Okay. It's taking too much time to find a free island spot and I'm confused why it's taking 30 seconds or more to do that. Anyway, I need to make this async.
