### ISSUE TITLE
/is 

### ISSUE THREAD

**Issue by greggsss** [BentoBoxWorld/BSkyBlock#221]
#### Describe the bug 

/is wont work at all, updated to the new versions

#### Steps to reproduce the behavior

upgrade to latest plugins and type /is

#### Expected behavior
 

well should to to island

##### BentoBox Version (Mandatory)

30.11 21:07:09 [Server] Startup [20:07:09 INFO]: Running PAPER 1.14.4.
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: BentoBox version: 1.8.0
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: Database: JSON
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: Loaded Game Worlds:
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: Loaded Addons:
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: BSkyBlock 1.8.0 (ENABLED)
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: Challenges 0.8.0-1.6.0 (ENABLED)
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: Level 1.9.0 (ENABLED)
30.11 21:07:09 [Server] Startup [20:07:09 INFO]: Warps 1.8.2 (ENABLED)
```
_______
```

#### Plugins (Optional)

Plugins (39): AsyncWorldEdit, AuthMe, BentoBox, ChatExpressions*, ChatInjector*, ChatReaction, Citizens, CommandNPC*, CoreProtect, CrazyCrates, CustomHeads*, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FeatherBoard*, HolographicDisplays, Item2Chat, JukeBox, LibsDisguises, Lottery, MVdWPlaceholderAPI*, NoPoppyDrop*, NoteBlockAPI, PermissionsEx*, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, ShopGUIPlus, StaffChat, SuperTrails*, TAB, Vault, VoidSpawn, WildStacker, WorldEdit, WorldGuard, zAuctionHouseV2*
```
_______
```
 
### Additional context (Optional)

30.11 21:03:44 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'is' in world.bentobox.bskyblock.commands.IslandCommand(island)
30.11 21:03:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
30.11 21:03:44 [Server] INFO Caused by: java.lang.NullPointerException
30.11 21:03:44 [Server] INFO at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.isIsland(DefaultNewIslandLocationStrategy.java:97) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.getNextLocation(DefaultNewIslandLocationStrategy.java:47) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.managers.island.NewIsland.newIsland(NewIsland.java:169) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.managers.island.NewIsland.<init>(NewIsland.java:52) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.managers.island.NewIsland$Builder.build(NewIsland.java:142) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.makeIsland(IslandCreateCommand.java:97) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.execute(IslandCreateCommand.java:85) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bskyblock.commands.IslandCommand.lambda$execute$1(IslandCommand.java:79) ~[?:?]
30.11 21:03:44 [Server] INFO at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_222]
30.11 21:03:44 [Server] INFO at world.bentobox.bskyblock.commands.IslandCommand.execute(IslandCommand.java:79) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
30.11 21:03:44 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
30.11 21:03:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-230]
30.11 21:03:44 [Server] INFO ... 16 more

**Comment by ghost** [comment]
also switching back to the version i was using before fixed it

**Comment by tastybento** [comment]
What was the previous version?

**Comment by ghost** [comment]
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: Running PAPER 1.14.4.
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: BentoBox version: 1.8.0
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: Database: JSON
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: Loaded Game Worlds:
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: Loaded Addons:
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: BSkyBlock 1.8.0 (ENABLED)
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: Challenges 0.8.0-1.6.0 (ENABLED)
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: Level 1.8.0 (ENABLED)
30.11 21:14:00 [Server] Startup [20:14:00 INFO]: Warps 1.8.2 (ENABLED)


this was the old

**Comment by tastybento** [comment]
I'm confused. Which version did you update from and to? It looks like 1.8.0 to 1.8.0 of BentoBox?

**Comment by ghost** [comment]
hm thats weird i though i put the 1.9.0, either way me updating to level 1.9.0 still messed up bskyblock as a whole

**Comment by tastybento** [comment]
ok, let me check into it.

**Comment by ghost** [comment]
thank you
