### ISSUE TITLE
console error spam

### ISSUE THREAD

**Issue by GizliBaskan** [BentoBoxWorld/BSkyBlock#298]
`[14:32:25] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between bskyblock_world and everything
[14:32:25] [Server thread/WARN]: 	at org.bukkit.Location.distanceSquared(Location.java:510)
[14:32:25] [Server thread/WARN]: 	at org.bukkit.Location.distance(Location.java:493)
[14:32:25] [Server thread/WARN]: 	at me.zombie_striker.pixelprinter.PixelPrinter$6.run(PixelPrinter.java:216)
[14:32:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[14:32:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[14:32:25] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
[14:32:25] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[14:32:25] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[14:32:25] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[14:32:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

please help, I did accidentally remove my island bedrock
probably because of the error
what can i do

- I deleted the database
but thats error continues

**Comment by tastybento** [comment]
It's due to a plugin called PixelPrinter. Delete that plugin's database or files and you should be good.
