### ISSUE TITLE
Challenges bug ?

### ISSUE THREAD

**Issue by Orakha** [BentoBoxWorld/BSkyBlock#320]
the commands / is challenge" and "/ bsbadmin challenge" no longer works, it is noted" command unknown "

**Comment by Poslovitch** [comment]
Is the Challenges addon installed?

**Comment by Orakha** [comment]
is there anything to add since the 2 last days ? 
because before yesterday i was creating challenges just with the /bsbadmin challenge , and since the new version is out it's not working :/

**Comment by BONNe** [comment]
Yea... we kinda cannot help, as we do not know anything about your server, and we cannot read minds. 

Probably if you would follow bug report template we could try to help, but now... nop... sorry.

**Comment by Orakha** [comment]
i gonna try to put the addon and i'll tell u if i patch it

**Comment by Orakha** [comment]
OKAY I installed the addon

[21:11:04] [Server thread/INFO]: [BentoBox] [Challenges] Loading challenges...
[21:11:07] [Server thread/ERROR]: [BentoBox] [Challenges] Cannot find BSkyBlock_competent challenge for BSkyBlock_competent
[21:11:07] [Server thread/ERROR]: [BentoBox] [Challenges] Challenge Level 'BSkyBlock_competent' is not valid and skipped
[21:11:07] [Server thread/ERROR]: [BentoBox] Skipping Challenges due to an unhandled exception...
[21:11:07] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException
        at world.bentobox.challenges.ChallengesManager.loadChallenge(ChallengesManager.java:266)
        at world.bentobox.challenges.ChallengesManager.loadChallenge(ChallengesManager.java:248)
        at world.bentobox.challenges.ChallengesManager.isValidLevel(ChallengesManager.java:479)
        at world.bentobox.challenges.ChallengesManager.loadLevel(ChallengesManager.java:327)
        at world.bentobox.challenges.ChallengesManager.loadLevel(ChallengesManager.java:308)
        at java.util.ArrayList.forEach(Unknown Source)
        at world.bentobox.challenges.ChallengesManager.loadAndValidate(ChallengesManager.java:215)
        at world.bentobox.challenges.ChallengesManager.load(ChallengesManager.java:209)
        at world.bentobox.challenges.ChallengesManager.<init>(ChallengesManager.java:184)
        at world.bentobox.challenges.ChallengesAddon.onEnable(ChallengesAddon.java:151)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:221)
        at java.util.ArrayList.forEach(Unknown Source)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:167)
        at world.bentobox.bentobox.BentoBox.lambda$onEnable$2(BentoBox.java:177)
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
        at java.lang.Thread.run(Unknown Source)

**Comment by BONNe** [comment]
I have seen this error myself.
The challenges is not loading up because of recent changes in error handling. 

But in a nutshell, BSkyBlock_competent is broken. For some reason, it does not contain valid information. In my case, it was forcefully closed server in saving time. 

To solve it, you should either use database backup for challenges and levels (if you have) or just remove challenges and challengesLevel folders from the database and create (import) challenges again.

sorry.

**Comment by Orakha** [comment]
ok i found the problem , i created a level named " expert" and i couldn't change the picture of it or change any informations into it , so i just deleted it and it worked :)
