### ISSUE TITLE
When I was in the use of the file server appeared 'An internal error occurred while accempting to perform this command

### ISSUE THREAD

**Issue by qq2719035729** [BentoBoxWorld/BSkyBlock#351]
Problems such as the topic

**Comment by Poslovitch** [comment]
Well... We need a lot more info about it, don't you think?

- /bbox v
- /ver
- Which file were you editing?

**Comment by qq2719035729** [comment]
The main use 'AOneblock 1.1.7' BSkyblock 1.13.1
 '

**Comment by Poslovitch** [comment]
Please provide the actual output of the commands I requested. They provide way more info than just a handwritten "I use is".

**Comment by Poslovitch** [comment]
You should also provide use the stacktrace of the error.

> An internal error occurred while accempting to perform this command

That is what you get when there's an error IG, but then the stacktrace shows up in the console.

Without the stacktrace, we won't be able to know "what's wrong".

**Comment by qq2719035729** [comment]
org.bukkit.command.CommandException: Unhandled exception executing 'is' in world.bentobox.aoneblock.commands.IslandCommand(is)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.isIsland(DefaultNewIslandLocationStrategy.java:93) ~[?:?]
	at world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.getNextLocation(DefaultNewIslandLocationStrategy.java:49) ~[?:?]
	at world.bentobox.bentobox.managers.island.NewIsland.newIsland(NewIsland.java:177) ~[?:?]
	at world.bentobox.bentobox.managers.island.NewIsland.<init>(NewIsland.java:52) ~[?:?]
	at world.bentobox.bentobox.managers.island.NewIsland$Builder.build(NewIsland.java:149) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.makeIsland(IslandCreateCommand.java:96) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.execute(IslandCreateCommand.java:84) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
	at world.bentobox.aoneblock.commands.IslandCommand.lambda$execute$1(IslandCommand.java:81) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_181]
	at world.bentobox.aoneblock.commands.IslandCommand.execute(IslandCommand.java:81) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	... 16 more
[16:41:51] [Server thread/INFO]: Stopping the server

**Comment by Poslovitch** [comment]
Great, thanks.
Could you please provide the output of `/bbox v` and `/ver`?

**Comment by qq2719035729** [comment]
![无标题](https://user-images.githubusercontent.com/30896160/86509012-5357a700-be17-11ea-82fc-7753405fe584.png)

**Comment by Poslovitch** [comment]
Thanks.
This seems to be related to BentoBox, I'm moving this issue to its repo.
