### ISSUE TITLE
Blueprints refuse to load

### ISSUE THREAD

**Issue by Budderman18** [BentoBoxWorld/BSkyBlock#451]
### Expected behavior

blueprints load and islands can be created. 

### Observed/Actual behavior

Islands cant be created. All blueprints show this message: I have not edited defaults nor have i created my own

Could not load blueprint classic-lshape Entry is outside of the target directory

### Steps/models to reproduce

start a server with the plugin

### BentoBox version

[21:04:47 INFO]: Running PAPER 1.18.1.
[21:04:47 INFO]: BentoBox version: 1.19.0
[21:04:47 INFO]: Database: JSON
[21:04:47 INFO]: Loaded Game Worlds:
[21:04:47 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[21:04:47 INFO]: Loaded Addons:
[21:04:47 INFO]: Biomes 1.14.0 (ENABLED)
[21:04:47 INFO]: BSkyBlock 1.15.2 (ENABLED)
[21:04:47 INFO]: Challenges 0.8.4 (ENABLED)
[21:04:47 INFO]: ControlPanel 1.13.0 (ENABLED)
[21:04:47 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[21:04:47 INFO]: Level 2.8.1 (ENABLED)
[21:04:47 INFO]: Limits 1.17.2 (ENABLED)
[21:04:47 INFO]: Warps 1.11.1 (ENABLED)

### Plugin list

Plugins (77): ajParkour, AutoKiller*, BedrockPlayerManager, BedWars, BentoBox, betterbroadcaster, BuildBattle, BuycraftX, Citizens, ClearLag, CommandHook, CommandSigns, ConsoleSpamFix, CrazyAuctions, Curses, Duels, Essentials, Essentials_WarpGUI, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsSpawn, F3NPerm, Factions, floodgate, Geyser-Spigot, gProtector, GriefPrevention, GroupManager, HideAndSeek, HoloExtension, HolographicDisplays, HungerGames, Images, JukeBox, KillerMoney*, LibsDisguises, Lobbys*, Maintenance, MinerWare, MobArena, Morphy, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MultiWorldMoney*, NoteBlockAPI, Parties, PlaceholderAPI, PlotSquared, PlugReloader*, Prison, ProtocolLib, RandomTeleport, ServersNPC, SignShop, SilkSpawners, SkQuery, Skript, SkyblockOres, Skywars, SpigotPing, SpleefX, StaffChat, StartupCommands*, TheBridge, Themis, TimeManager, TitleManager, TowerDefense*, UltraCosmetics, Vault, Votifier, VotingPlugin, Warns*, WorldEdit

**Comment by tastybento** [comment]
Sorry, I cannot replicate. I used the download from https://download.bentobox.world and the latest Paper server and everything works. I tried on two servers. What OS are you using?

When you say "All blueprints show this message:" where is this message shown? What do you do to trigger this message? Please share/paste some logs so I can see it and describe the steps you used.

Proof of success:
<img width="840" alt="Screen Shot 2021-12-21 at 6 27 22 PM 1" src="https://user-images.githubusercontent.com/4407265/147025462-476a2d5e-0240-4b93-8eb7-8382583884c2.png">

```
> bbox v
[18:31:47 INFO]: Running PAPER 1.18.1.
[18:31:47 INFO]: BentoBox version: 1.19.0
[18:31:47 INFO]: Database: JSON
[18:31:47 INFO]: Loaded Game Worlds:
[18:31:47 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[18:31:47 INFO]: Loaded Addons:
[18:31:47 INFO]: Biomes 1.14.0 (ENABLED)
[18:31:47 INFO]: BSkyBlock 1.15.2 (ENABLED)
[18:31:47 INFO]: Challenges 0.8.4 (ENABLED)
[18:31:47 INFO]: ControlPanel 1.13.0 (ENABLED)
[18:31:47 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[18:31:47 INFO]: Level 2.8.1 (ENABLED)
[18:31:47 INFO]: Limits 1.17.2 (ENABLED)
[18:31:47 INFO]: Warps 1.11.1 (ENABLED)
```

**Comment by Budderman18** [comment]
Paper version: This server is running Paper version git-Paper-92 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 264b11d)

Pc is running Windows 10 version 21H2

the "could not load" message occurs near the end of startup, its not with the rest of BentoBox's load messages

latest log: https://drive.google.com/file/d/1G8vxqQkxRTKHvit94DcdgNKXGxrK6MdO/view?usp=sharing

**Comment by BONNe** [comment]
Do you have `/plugins/bentobox/addons/bskyblock/blueprints` folder?
Also, have you somehow changed any files inside blueprints folder?

**Comment by Budderman18** [comment]
The folder exists and everything is there. As i mentioned, i have not made any changes to blueprints

**Comment by Budderman18** [comment]
Update: The latest dev build does not fix the issue, however there is now a more detailed error:

 [BentoBox] Could not load blueprint classic-lshape Entry is outside of the target directory
[19:48:35 ERROR]: [BentoBox] java.io.IOException: Entry is outside of the target directory
        at BentoBox-1.19.1-SNAPSHOT-b2199.jar//world.bentobox.bentobox.managers.BlueprintClipboardManager.unzipFiles(BlueprintClipboardManager.java:211)
        at BentoBox-1.19.1-SNAPSHOT-b2199.jar//world.bentobox.bentobox.managers.BlueprintClipboardManager.unzip(BlueprintClipboardManager.java:195)
        at BentoBox-1.19.1-SNAPSHOT-b2199.jar//world.bentobox.bentobox.managers.BlueprintClipboardManager.loadBlueprint(BlueprintClipboardManager.java:99)
        at BentoBox-1.19.1-SNAPSHOT-b2199.jar//world.bentobox.bentobox.managers.BlueprintsManager.loadBlueprints(BlueprintsManager.java:310)
        at BentoBox-1.19.1-SNAPSHOT-b2199.jar//world.bentobox.bentobox.managers.BlueprintsManager.lambda$loadBlueprintBundles$5(BlueprintsManager.java:197)
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by BONNe** [comment]
The weird part is that error is complaining about missing blueprint files.
I have never encountered error like that.

Maybe you could try to remove blueprints directory completely and let plugin to regenerate them.

**Comment by Budderman18** [comment]
Deleted the blueprints folder. It regenerates them and still says the same thing
