### ISSUE TITLE
Block placement

### ISSUE THREAD

**Issue by masterhacka** [BentoBoxWorld/BSkyBlock#461]
### Expected behavior

Block placement should be restricted.

### Observed/Actual behavior

Since Borders plugin doesn‘t work with 1.18 it is possible to place a block outside the island.

### Steps/models to reproduce

Step at the outest point of your island and you will be able to place one more block. Unfortunately it is not possible to remove it.

### BentoBox version

[15:26:12] [Server thread/INFO]: Ausführen von PAPER 1.18.1.
[15:26:12] [Server thread/INFO]: BentoBox version: 1.19.0
[15:26:12] [Server thread/INFO]: Datenbank: JSON
[15:26:12] [Server thread/INFO]: Geladene Spielewelten:
[15:26:12] [Server thread/INFO]: ASkyBlock (BSkyBlock): Oberwelt, Nether, End
[15:26:12] [Server thread/INFO]: oneblock_world (OneBlock): Oberwelt, Nether, End
[15:26:12] [Server thread/INFO]: Geladene Addons:
[15:26:12] [Server thread/INFO]: AOneBlock 1.9.0 (ENABLED)
[15:26:12] [Server thread/INFO]: Biomes 1.14.0 (ENABLED)
[15:26:12] [Server thread/INFO]: Border 3.2.0 (INCOMPATIBLE)
[15:26:12] [Server thread/INFO]: BSkyBlock 1.15.2 (ENABLED)
[15:26:12] [Server thread/INFO]: Challenges 0.8.4 (ENABLED)
[15:26:12] [Server thread/INFO]: ControlPanel 1.13.0 (ENABLED)
[15:26:12] [Server thread/INFO]: DimensionalTrees 1.6.0 (ENABLED)
[15:26:12] [Server thread/INFO]: Greenhouses 1.6.0 (ENABLED)
[15:26:12] [Server thread/INFO]: IslandFly 1.8.1 (ENABLED)
[15:26:12] [Server thread/INFO]: Level 2.9.0 (ENABLED)
[15:26:12] [Server thread/INFO]: Limits 1.19.0 (ENABLED)
[15:26:12] [Server thread/INFO]: Warps 1.11.2 (ENABLED)

**Comment by tastybento** [comment]
Border works with 1.18.1. But, even without border, the blocks should not be possible to place outside your island unless you are op. Please share the `/is info` output and the coordinate of the blocks that you say you can place. I need to check that because it sounds like a bug.

Did you download the WorldBorderAPI plugin and put it in your plugins folder? Download from https://github.com/yannicklamprecht/WorldBorderAPI/releases 

```
> bbox v
[16:18:43 INFO]: Running PAPER 1.18.1.
[16:18:43 INFO]: BentoBox version: 1.19.0
[16:18:43 INFO]: Database: JSON
[16:18:43 INFO]: Loaded Game Worlds:
[16:18:43 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[16:18:43 INFO]: Loaded Addons:
[16:18:43 INFO]: AOneBlock 1.9.0 (ENABLED)
[16:18:43 INFO]: Bank 1.4.0-SNAPSHOT-LOCAL (DISABLED)
[16:18:43 INFO]: Biomes 1.14.0 (ENABLED)
[16:18:43 INFO]: Border 3.2.0 (ENABLED)
[16:18:43 INFO]: Greenhouses 1.7.0-SNAPSHOT-b312 (ENABLED)
[16:18:43 INFO]: Limits 1.19.1-SNAPSHOT-LOCAL (ENABLED)
[16:18:43 INFO]: TwerkingForTrees 1.4.3-SNAPSHOT-LOCAL (ENABLED)
[16:18:43 INFO]: Upgrades 0.3.0-SNAPSHOT-LOCAL (ENABLED)
[16:18:43 INFO]: Warps 1.11.2 (ENABLED)
```
<img width="842" alt="Screen Shot 2022-01-09 at 4 16 27 PM" src="https://user-images.githubusercontent.com/4407265/148707055-f6336514-284e-4fed-9693-ff7cddbbd30c.png">

**Comment by masterhacka** [comment]
I am sorry the problem is AOneBlock. 

![2022-01-10_14 53 41](https://user-images.githubusercontent.com/9753608/148777623-180329b3-6ad9-4356-98fc-0f30838193f1.png)

**Comment by masterhacka** [comment]
The border plugin shows the following in server logs, even with WorldBorderAPI installed:

`[15:01:35] [Server thread/INFO]: [BentoBox] Enabling Border (3.2.0)...
[15:01:35] [Server thread/WARN]: [BentoBox] Skipping Border as it is incompatible with the current version of BentoBox or of server software...
[15:01:35] [Server thread/WARN]: [BentoBox] NOTE: The addon is referring to no longer existing classes.
[15:01:35] [Server thread/WARN]: [BentoBox] NOTE: DO NOT report this as a bug from BentoBox.
[15:01:35] [Server thread/ERROR]: [BentoBox] Please report this stack trace to the addon's author(s): [tastybento] 
java.lang.NoSuchFieldError: BARRIER
	at world.bentobox.border.listeners.ShowBarrier.<clinit>(ShowBarrier.java:36) ~[?:?]
	at world.bentobox.border.listeners.PlayerBorder.<init>(PlayerBorder.java:30) ~[?:?]
	at world.bentobox.border.Border.onEnable(Border.java:52) ~[?:?]
	at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:306) ~[BentoBox-1.19.0.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:248) ~[BentoBox-1.19.0.jar:?]
	at world.bentobox.bentobox.BentoBox.completeSetup(BentoBox.java:185) ~[BentoBox-1.19.0.jar:?]
	at world.bentobox.bentobox.BentoBox.lambda$onEnable$0(BentoBox.java:170) ~[BentoBox-1.19.0.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-140]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-140]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]`

**Comment by masterhacka** [comment]
I got the Border plugin fixed with recreating the config
