### ISSUE TITLE
Blue Print Bug

### ISSUE THREAD

**Issue by AgatraA** [BentoBoxWorld/BSkyBlock#468]
### Expected behavior

I can create a normal island like in the tutorials. I can make a custom island.

### Observed/Actual behavior

When i tried creating an island in resulted in creating 
![image](https://user-images.githubusercontent.com/74516574/156277210-062f9782-8536-46a0-bdd8-8cea87e41c6c.png)
and when im making a custom island and saving it. it says an internal error occured.

### Steps/models to reproduce

I think i just download it with some other plugins and started the server.

### BentoBox version

1.120.0

### Plugin list

![image](https://user-images.githubusercontent.com/74516574/156277410-b184235d-63f4-4910-a74f-f3ee29e588cb.png)

**Comment by AgatraA** [comment]
Also when i try to load a blueprint it shows a bunch of error msg

```
[03:56:27] [Server thread/INFO]: Agatra issued server command: /bsb bp load end-island
[03:56:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'bsb bp load end-island' in world.bentobox.bskyblock.BSkyBlock$2(bsbadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchFieldError: OLD_GROWTH_BIRCH_FOREST
        at world.bentobox.bentobox.database.json.adapters.BiomeTypeAdapter.<init>(BiomeTypeAdapter.java:42) ~[?:?]
        at world.bentobox.bentobox.database.json.BentoboxTypeAdapterFactory.create(BentoboxTypeAdapterFactory.java:60) ~[?:?]
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.Gson.fromJson(Gson.java:886) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at com.google.gson.Gson.fromJson(Gson.java:825) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at world.bentobox.bentobox.managers.BlueprintClipboardManager.loadBlueprint(BlueprintClipboardManager.java:107) ~[?:?]
        at world.bentobox.bentobox.managers.BlueprintClipboardManager.load(BlueprintClipboardManager.java:83) ~[?:?]
        at world.bentobox.bentobox.managers.BlueprintClipboardManager.load(BlueprintClipboardManager.java:130) ~[?:?]
        at world.bentobox.bentobox.api.commands.admin.blueprints.AdminBlueprintLoadCommand.execute(AdminBlueprintLoadCommand.java:35) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:273) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:246) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        ... 18 more
```

**Comment by BONNe** [comment]
BentoBox 1.20 contains features from Minecraft 1.18.
The error you encounter is one of 1.18 feature. 

I would suggest to use BentoBox 1.19

**Comment by AgatraA** [comment]
Oooooo okokkk thanksss

**Comment by AgatraA** [comment]
> BentoBox 1.20 contains features from Minecraft 1.18. The error you encounter is one of 1.18 feature.
> 
> I would suggest to use BentoBox 1.19

how do i get that tho

**Comment by tastybento** [comment]
Here you go: https://github.com/BentoBoxWorld/BentoBox/releases/tag/1.19.0
