### ISSUE TITLE
Error. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [BentoBoxWorld/BSkyBlock#47]
[16:10:35] [Server thread/ERROR]: Could not load 'plugins/bskyblock-1.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:329) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by Poslovitch** [comment]
https://github.com/BentoBoxWorld/bentobox/wiki/Install-Bentobox
