### ISSUE TITLE
Maybe have a conflict

### ISSUE THREAD

**Issue by Y-Yuw** [BentoBoxWorld/BSkyBlock#474]
### Expected behavior

create a island

### Observed/Actual behavior

[16:09:51] [Server thread/ERROR]: [BentoBox] New island for user test was not reserved!
[16:09:51] [Server thread/ERROR]: [BentoBox] Cannot load island. Overlapping: 8ab6c3a1-7664-4d81-ab0f-87e2bb7d655c
[16:09:51] [Server thread/ERROR]: [BentoBox] Location: Location{world=CraftWorld{name=bskyblock_world},x=0.0,y=0.0,z=0.0,pitch=0.0,yaw=0.0}
[16:09:51] [Server thread/ERROR]: [BentoBox] Same owner duplicate.
[16:09:51] [Server thread/ERROR]: [BentoBox] Failed to make island! Island could not be added to the grid.
[16:09:51] [Server thread/ERROR]: [BentoBox] Could not create island for player. commands.island.create.unable-create-island

### Steps/models to reproduce

/island

### BentoBox version

[16:13:04] [Server thread/INFO]: 服务器： 无效 (87A458D6 (MC: 1.16.5)) 1.16.5
[16:13:04] [Server thread/INFO]: BentoBox 版本： 1.16.6
[16:13:04] [Server thread/INFO]: 数据库： JSON
[16:13:04] [Server thread/INFO]: 已载入的游戏世界：
[16:13:04] [Server thread/INFO]: 已载入的附加组件：
[16:13:04] [Server thread/INFO]: Biomes 1.14.0 (DISABLED)
[16:13:04] [Server thread/INFO]: BSkyBlock 1.15.2 (ERROR)
[16:13:04] [Server thread/INFO]: Challenges 0.8.4 (DISABLED)
[16:13:04] [Server thread/INFO]: Chat 1.1.4 (ENABLED)
[16:13:04] [Server thread/INFO]: ControlPanel 1.13.0 (ENABLED)
[16:13:04] [Server thread/INFO]: DimensionalTrees 1.6.0 (ENABLED)
[16:13:04] [Server thread/INFO]: Level 2.8.1 (ENABLED)
[16:13:04] [Server thread/INFO]: Visit 1.3.0 (ENABLED)
[16:13:04] [Server thread/INFO]: Warps 1.10.2 (DISABLED)

### Plugin list

 LuckPerms, OverallGamerule, EasyPlanting, NBTAPI, Vault, LuckPermsGUI, YukiNoaAPI, BentoBox, Essentials, EssentialsChat, EssentialsGeoIP, BanIt, JustMoney, ShopChest, EssentialsSpawn, CatSeedLogin

**Comment by BONNe** [comment]
It sounds like some database corruption that happened. 
Somehow your database has multiple islands that occupy the same spot (or overlap). This should not happen in normal circumstances... 
I am not even sure how you ended up in this situation.

Is it affecting all players or just a specific one?

In general, by looking at error messages that are printed out:
A player with the name `test` had an island or had a reserved spot for an island.
But the island now is not owned by the player or the player is not a part of that island.

If you visit that island and write `/[admin_cmd] info` it should print out information about the spot: who is the owner, who are the team members, and what is island area.

Have you switched server mode from `online` to `offline` (or via versa)? As that may affect the database and ruin some things.

**Comment by Y-Yuw** [comment]
> It sounds like some database corruption that happened. Somehow your database has multiple islands that occupy the same spot (or overlap). This should not happen in normal circumstances... I am not even sure how you ended up in this situation.
> 
> Is it affecting all players or just a specific one?
> 
> In general, by looking at error messages that are printed out: A player with the name `test` had an island or had a reserved spot for an island. But the island now is not owned by the player or the player is not a part of that island.
> 
> If you visit that island and write `/[admin_cmd] info` it should print out information about the spot: who is the owner, who are the team members, and what is island area.
> 
> Have you switched server mode from `online` to `offline` (or via versa)? As that may affect the database and ruin some things.

I just made the server 5mins ago and the player is just me.The island world is empty

**Comment by Y-Yuw** [comment]
Should I delete my database?

**Comment by BONNe** [comment]
Yes, you can delete `Islands`, `Players` and `Names` databases. It should solve the issue.

**Comment by Y-Yuw** [comment]
I think the plugin BSkyBlock doesn't work

**Comment by Y-Yuw** [comment]
[16:40:58] [Server thread/INFO]: [BentoBox] [BSkyBlock] Creating BSkyBlock's Nether...
[16:40:58] [Server thread/ERROR]: [BentoBox] Skipping BSkyBlock due to an unhandled exception...
[16:40:58] [Server thread/ERROR]: [BentoBox] java.lang.IllegalArgumentException: Illegal dimension
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createWorld(CraftServer.java:924)
        at org.bukkit.Bukkit.createWorld(Bukkit.java:535)
        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325)
        at world.bentobox.bskyblock.BSkyBlock.getWorld(BSkyBlock.java:130)
        at world.bentobox.bskyblock.BSkyBlock.createWorlds(BSkyBlock.java:107)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:300)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:246)
        at world.bentobox.bentobox.BentoBox.completeSetup(BentoBox.java:185)
        at world.bentobox.bentobox.BentoBox.lambda$onEnable$0(BentoBox.java:170)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:996)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:942)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265)
        at java.base/java.lang.Thread.run(Thread.java:833)

[16:40:58] [Server thread/INFO]: [BentoBox] Enabling other addons...
[16:40:58] [Server thread/INFO]: [BentoBox] Enabling Level (2.8.1)...
[16:40:58] [Server thread/WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : caveblock-world
[16:40:58] [Server thread/WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : acidisland_world
[16:40:58] [Server thread/INFO]: [BentoBox] Enabling Biomes (1.14.0)...
[16:40:58] [Server thread/ERROR]: [BentoBox] [Biomes] Biomes could not hook into any GameMode so will not do anything!
[16:40:58] [Server thread/INFO]: [BentoBox] Biomes is disabled.
[16:40:58] [Server thread/INFO]: [BentoBox] Enabling Challenges (0.8.4)...
[16:40:58] [Server thread/INFO]: [BentoBox] [Challenges] Loading challenges...
[16:40:58] [Server thread/ERROR]: [BentoBox] [Challenges] Challenges could not hook into AcidIsland or BSkyBlock so will not do anything!

**Comment by BONNe** [comment]
Hmm, 
Do you use BSkyBlock world generator, or do you use your custom world generation?

**Comment by Y-Yuw** [comment]
BSkyBlock
![image](https://user-images.githubusercontent.com/89560808/171133184-6611ca40-cec7-4d4c-acfd-2c778fa292e9.png)

**Comment by BONNe** [comment]
hmm, then it is weird.

It says that it cannot build `NETHER` dimension, because the dimension field has an incorrect value.
Maybe you could try to remove `bskyblock_world_nether` world?

**Comment by Y-Yuw** [comment]
there is no bskyblock_world_nether
![image](https://user-images.githubusercontent.com/89560808/171134666-2be89a84-fe21-4c1f-976a-68b86823b841.png)

**Comment by Y-Yuw** [comment]
It is [CatServer]
 CatServer version 1.16.5-87a458d6

**Comment by Y-Yuw** [comment]
> Yea, I tried... It looks like the issue is with CatServer world generation. They are either doing something wrong by _Spigot standards_ or do not support nether and the end dimensions.
> 
> If you are not interested in nether and the end dimensions, you can disable them in BSkyBlock `config.yml`: `world.nether.generate` and `world.end.generate` by setting them both to false.
> 
> As BentoBox is built upon Spigot, there is nothing we can do, as CatServer is way beyond our supported engines.

ok,I understand.Thank you so much for your assistance.

**Comment by Y-Yuw** [comment]
I have a question,I see that the catserver use the Spigot.

**Comment by Y-Yuw** [comment]
![image](https://user-images.githubusercontent.com/89560808/171141949-b5b58e06-b1c6-4e71-8fd1-c59f0d23df9a.png)
This problem is because the catserver also uses the bukkit?

**Comment by BONNe** [comment]
Spigot is build upon Bukkit. Bukkit is a predecessor of Spigot. 

But the issue is with CatServer. Technically you could create worlds with just a Bukkit, but there would be different issues with operating all systems. 

Their support of the Spigot is either not complete or is wrongly implemented.

**Comment by Y-Yuw** [comment]
Thank you for your respond vary much!The problem was fixed by CatServer.
