### ISSUE TITLE
Player worlds deleted and this error on startup:

### ISSUE THREAD

**Issue by timbo2040** [BentoBoxWorld/BSkyBlock#517]
### Expected behavior

Server starts and plugin loads properly, world don't disappear

### Observed/Actual behavior

Plugin loads but with this error and player islands are gone after restart

### Steps/models to reproduce

Newest version of BentoBox and BSkyBlock, this happens on startup for no apparent reason.

### BentoBox version

[21:27:24 INFO]: Running PAPER 1.20.4.
[21:27:24 INFO]: (git-Paper-478 (MC: 1.20.4))
[21:27:24 INFO]: BentoBox version: 2.3.0
[21:27:24 INFO]: Database: JSON
[21:27:24 INFO]: Loaded Game Worlds:
[21:27:24 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[21:27:24 INFO]: Loaded Addons:
[21:27:24 INFO]: Bank 1.7.1 (DISABLED)
[21:27:24 INFO]: Biomes 2.1.1 (ENABLED)
[21:27:24 INFO]: Border 4.2.1 (ENABLED)
[21:27:24 INFO]: BSkyBlock 1.17.1 (ENABLED)
[21:27:24 INFO]: Challenges 1.3.0 (ENABLED)
[21:27:24 INFO]: Chat 1.1.4 (ENABLED)
[21:27:24 INFO]: CheckMeOut 1.1.1 (ENABLED)
[21:27:24 INFO]: ControlPanel 1.13.1 (ENABLED)
[21:27:24 INFO]: DimensionalTrees 1.7.0 (ENABLED)
[21:27:24 INFO]: ExtraMobs 1.12 (ENABLED)
[21:27:24 INFO]: Level 2.12.0 (ENABLED)
[21:27:24 INFO]: Visit 1.6.0 (ENABLED)
[21:27:24 INFO]: Warps 1.14.0 (ENABLED)

### Plugin list

AntiSwear, BentoBox, BentoBox-Bank, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-CheckMeOut, BentoBox-Level, BentoBox-Visit, BentoBox-Warps, RandomSpawnEffect, ViaBackwards, ViaVersion

### Other

Here is the console error: 

```
[21:22:45 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'BSkyBlock-1.17.1-SNAPSHOT-LOCAL.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: world/bentobox/bentobox/api/addons/Pladdon
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.4.jar:git-Paper-478]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.4.jar:git-Paper-478]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.4.jar:git-Paper-478]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.4.jar:git-Paper-478]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-478]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-478]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-478]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-478]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-478]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: world/bentobox/bentobox/api/addons/Pladdon
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.4.jar:git-Paper-478]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: world.bentobox.bentobox.api.addons.Pladdon
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.4.jar:git-Paper-478]
        ... 9 more
```

**Comment by tastybento** [comment]
Hmm, I cannot replicate. Is BSkyBlock in the `plugins/BentoBox/addons` folder? The error says it is in the plugins folder, but BentoBox addons need to be in the addons folder.

**Comment by timbo2040** [comment]
> Hmm, I cannot replicate. Is BSkyBlock in the `plugins/BentoBox/addons` folder? The error says it is in the plugins folder, but BentoBox addons need to be in the addons folder.
> 
> 
> 
> Also, from the reports you share, it looks like it is loaded? Can you share the steps?

I think it is all correct, I downloaded it from the website after picking my addons. Then I extracted and popped it into my plugins folder

**Comment by tastybento** [comment]
Yes, the addons, like BSkyBlock should not be in the plugins folder. They need to be in the addons folder.

**Comment by tastybento** [comment]
But, it seems you did have something working. Do you get this error all the time? Or did this just happen once?

**Comment by timbo2040** [comment]
> But, it seems you did have something working. Do you get this error all the time? Or did this just happen once?

It only worked the first time i ran the server. Making an island worked and everything but then it didnt work after that

**Comment by tastybento** [comment]
The error message references "BSkyBlock-1.17.1-SNAPSHOT-LOCAL.jar" which is a locally built jar file and not the one that is in the releases, so I don't know where that came from. If you built the code then cool, but you may want to remove that jar from plugins, or make sure it was built properly. The jar to use in the releases of this repo.

**Comment by timbo2040** [comment]
> The error message references "BSkyBlock-1.17.1-SNAPSHOT-LOCAL.jar" which is a locally built jar file and not the one that is in the releases, so I don't know where that came from. If you built the code then cool, but you may want to remove that jar from plugins, or make sure it was built properly. The jar to use in the releases of this repo.

Wait youre right.... i dont remember putting in my jar since it wasnt even done but thats gotta be it!

**Comment by tastybento** [comment]
Okay, closing for now.
