### ISSUE TITLE
MC 1.21.3 support

### ISSUE THREAD

**Issue by SlimeDog** [BentoBoxWorld/BSkyBlock#532]
### Expected behavior

Clean start-up

### Observed/Actual behavior

```
[17:18:09] [Server thread/INFO]: [BentoBox] Loading addons...
[17:18:09] [Paper Plugin Remapper Thread - 5/INFO]: [PluginRemapper] Remapping plugin 'plugins/BentoBox/addons/BSkyBlock-1.18.2-b776.jar'...
[17:18:10] [Paper Plugin Remapper Thread - 5/INFO]: [PluginRemapper] Done remapping plugin 'plugins/BentoBox/addons/BSkyBlock-1.18.2-b776.jar' in 391ms. 
[17:18:10] [Server thread/INFO]: [BentoBox-BSkyBlock] Loading server plugin BentoBox-BSkyBlock v1.18.2-SNAPSHOT-b776
[17:18:10] [Server thread/ERROR]: [BentoBox] Could not load config object! null
[17:18:10] [Server thread/ERROR]: [BentoBox] java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.createObject(YamlDatabaseHandler.java:152)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.loadObject(YamlDatabaseHandler.java:95)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:64)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:81)
        at BSkyBlock-1.18.2-b776-1730593089630.jar//world.bentobox.bskyblock.BSkyBlock.loadSettings(BSkyBlock.java:59)
        at BSkyBlock-1.18.2-b776-1730593089630.jar//world.bentobox.bskyblock.BSkyBlock.onLoad(BSkyBlock.java:40)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.managers.AddonsManager.initializeAddon(AddonsManager.java:254)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:191)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570) 
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) 
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:150)
        at BentoBox-2.7.0-b2740.jar//world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:172)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.ClassCastException: interface org.bukkit.block.Biome not an enum 
        at java.base/java.util.EnumSet.noneOf(EnumSet.java:115)
        at java.base/java.util.EnumSet.allOf(EnumSet.java:134)
        at com.google.common.base.Enums.populateCache(Enums.java:83)
        at com.google.common.base.Enums.getEnumConstants(Enums.java:96)
        at com.google.common.base.Platform.getEnumIfPresent(Platform.java:44)
        at com.google.common.base.Enums.getIfPresent(Enums.java:72)
        at BSkyBlock-1.18.2-b776-1730593089630.jar//world.bentobox.bskyblock.Settings.<init>(Settings.java:158)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        ... 31 more

[17:18:10] [Server thread/ERROR]: [BentoBox] [BSkyBlock] BSkyBlock settings could not load! Addon disabled.
[17:18:10] [Server thread/ERROR]: [BentoBox] Skipping BSkyBlock due to an unhandled exception...
```

### Steps/models to reproduce

- Update to Paper 1.21.3-11
- Start server
- Read console/log errors

### BentoBox version

```
> bbox version
[23:10:18 INFO]: Running PAPER 1.21.3.
[23:10:18 INFO]: (1.21.3-11-a6df4c8 (MC: 1.21.3))
[23:10:18 INFO]: BentoBox version: 2.7.0
[23:10:18 INFO]: Database: JSON
[23:10:18 INFO]: Loaded Game Worlds:
[23:10:18 INFO]: Loaded Addons:
[23:10:18 INFO]: BSkyBlock 1.18.2-SNAPSHOT-b776 (ERROR)
```

### Plugin list

N/A

**Comment by tastybento** [comment]
Yes, this is big and i'm working on it. 

Check out the warning when you start the server:
> [09:35:45] [Server thread/INFO]: Starting minecraft server version 1.21.3
> [09:35:45] [Server thread/INFO]: Loading properties
> [09:35:45] [Server thread/INFO]: This server is running CraftBukkit version 4354-Spigot-5eb8a94-c7aab7f (MC: 1.21.3) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
> [09:35:46] [Server thread/INFO]: *** This version of Spigot contains changes to some enums. If you notice that plugins no longer work after updating, please report this to the developers of those plugins first. ***
> [09:35:46] [Server thread/INFO]: *** If you cannot update those plugins, you can try setting `settings.compatibility.enum-compatibility-mode` to `true` in `bukkit.yml`. ***

My rant is on Discord but basically this breaks a LOT of things. Saving, code, etc. 

Anyway, it's going to be a bit of a slog to get it all rewritten.

**Comment by SlimeDog** [comment]
Understood. Every dev has the same issue. I can wait, since my servers are now for plugin testing only (mostly my own, but others are included if my servers used them in the olden days).

I don't Discord.

**Comment by SlimeDog** [comment]
Paper 1.21.3-15
BentoBox 2.7.1-b2748

Lots of ERROR reported on server start-up. I'm not sure they are actually errors, but here you go ...
```
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: en-US
[12:39:23] [Server thread/ERROR]: [BentoBox] setDefaultLanguage
[12:39:23] [Server thread/ERROR]: [BentoBox] getDefaultLanguage
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setUseEconomy
[12:39:23] [Server thread/ERROR]: [BentoBox] isUseEconomy
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: JSON
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabaseType
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabaseType
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: localhost
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabaseHost
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabaseHost
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 3306
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabasePort
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabasePort
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: bentobox
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabaseName
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabaseName
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: username
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabaseUsername
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabaseUsername
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: password
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabasePassword
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabasePassword
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 5
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabaseBackupPeriod
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabaseBackupPeriod
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 20
[12:39:23] [Server thread/ERROR]: [BentoBox] setMaxSavedPlayersPerTick
[12:39:23] [Server thread/ERROR]: [BentoBox] getMaxSavedPlayersPerTick
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 20
[12:39:23] [Server thread/ERROR]: [BentoBox] setMaxSavedIslandsPerTick
[12:39:23] [Server thread/ERROR]: [BentoBox] getMaxSavedIslandsPerTick
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 10
[12:39:23] [Server thread/ERROR]: [BentoBox] setMaximumPoolSize
[12:39:23] [Server thread/ERROR]: [BentoBox] getMaximumPoolSize
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setUseSSL
[12:39:23] [Server thread/ERROR]: [BentoBox] isUseSSL
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 
[12:39:23] [Server thread/ERROR]: [BentoBox] setDatabasePrefix
[12:39:23] [Server thread/ERROR]: [BentoBox] getDatabasePrefix
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 
[12:39:23] [Server thread/ERROR]: [BentoBox] setMongodbConnectionUri
[12:39:23] [Server thread/ERROR]: [BentoBox] getMongodbConnectionUri
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setClosePanelOnClickOutside
[12:39:23] [Server thread/ERROR]: [BentoBox] isClosePanelOnClickOutside
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: LIGHT_BLUE_STAINED_GLASS_PANE
[12:39:23] [Server thread/ERROR]: [BentoBox] setPanelFillerMaterial
[12:39:23] [Server thread/ERROR]: [BentoBox] getPanelFillerMaterial
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setUseCacheServer
[12:39:23] [Server thread/ERROR]: [BentoBox] isUseCacheServer
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 60
[12:39:23] [Server thread/ERROR]: [BentoBox] setPlayerHeadCacheTime
[12:39:23] [Server thread/ERROR]: [BentoBox] getPlayerHeadCacheTime
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 9
[12:39:23] [Server thread/ERROR]: [BentoBox] setHeadsPerCall
[12:39:23] [Server thread/ERROR]: [BentoBox] getHeadsPerCall
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 10
[12:39:23] [Server thread/ERROR]: [BentoBox] setTicksBetweenCalls
[12:39:23] [Server thread/ERROR]: [BentoBox] getTicksBetweenCalls
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setLogCleanSuperFlatChunks
[12:39:23] [Server thread/ERROR]: [BentoBox] isLogCleanSuperFlatChunks
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setLogGithubDownloadData
[12:39:23] [Server thread/ERROR]: [BentoBox] isLogGithubDownloadData
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setOverrideSafetyCheck
[12:39:23] [Server thread/ERROR]: [BentoBox] isOverrideSafetyCheck
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 1
[12:39:23] [Server thread/ERROR]: [BentoBox] setIslandNumber
[12:39:23] [Server thread/ERROR]: [BentoBox] getIslandNumber
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setHideUsedBlueprints
[12:39:23] [Server thread/ERROR]: [BentoBox] isHideUsedBlueprints
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 60
[12:39:23] [Server thread/ERROR]: [BentoBox] setInviteCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] getInviteCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 5
[12:39:23] [Server thread/ERROR]: [BentoBox] setCoopCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] getCoopCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 5
[12:39:23] [Server thread/ERROR]: [BentoBox] setTrustCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] getTrustCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 10
[12:39:23] [Server thread/ERROR]: [BentoBox] setBanCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] getBanCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 300
[12:39:23] [Server thread/ERROR]: [BentoBox] setResetCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] getResetCooldown
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setResetCooldownOnCreate
[12:39:23] [Server thread/ERROR]: [BentoBox] isResetCooldownOnCreate
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 10
[12:39:23] [Server thread/ERROR]: [BentoBox] setConfirmationTime
[12:39:23] [Server thread/ERROR]: [BentoBox] getConfirmationTime
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 0
[12:39:23] [Server thread/ERROR]: [BentoBox] setDelayTime
[12:39:23] [Server thread/ERROR]: [BentoBox] getDelayTime
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setKickConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] isKickConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setLeaveConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] isLeaveConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setResetConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] isResetConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setInviteConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] isInviteConfirmation
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 4
[12:39:23] [Server thread/ERROR]: [BentoBox] setNameMinLength
[12:39:23] [Server thread/ERROR]: [BentoBox] getNameMinLength
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 20
[12:39:23] [Server thread/ERROR]: [BentoBox] setNameMaxLength
[12:39:23] [Server thread/ERROR]: [BentoBox] getNameMaxLength
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setNameUniqueness
[12:39:23] [Server thread/ERROR]: [BentoBox] isNameUniqueness
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 5
[12:39:23] [Server thread/ERROR]: [BentoBox] setClearRadius
[12:39:23] [Server thread/ERROR]: [BentoBox] getClearRadius
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 64
[12:39:23] [Server thread/ERROR]: [BentoBox] setMinPortalSearchRadius
[12:39:23] [Server thread/ERROR]: [BentoBox] getMinPortalSearchRadius
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 64
[12:39:23] [Server thread/ERROR]: [BentoBox] setPasteSpeed
[12:39:23] [Server thread/ERROR]: [BentoBox] getPasteSpeed
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 1
[12:39:23] [Server thread/ERROR]: [BentoBox] setDeleteSpeed
[12:39:23] [Server thread/ERROR]: [BentoBox] getDeleteSpeed
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setKeepPreviousIslandOnReset
[12:39:23] [Server thread/ERROR]: [BentoBox] isKeepPreviousIslandOnReset
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: false
[12:39:23] [Server thread/ERROR]: [BentoBox] setSlowDeletion
[12:39:23] [Server thread/ERROR]: [BentoBox] isSlowDeletion
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 400
[12:39:23] [Server thread/ERROR]: [BentoBox] setSafeSpotSearchVerticalRange
[12:39:23] [Server thread/ERROR]: [BentoBox] getSafeSpotSearchVerticalRange
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 16
[12:39:23] [Server thread/ERROR]: [BentoBox] setSafeSpotSearchRange
[12:39:23] [Server thread/ERROR]: [BentoBox] getSafeSpotSearchRange
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: true
[12:39:23] [Server thread/ERROR]: [BentoBox] setGithubDownloadData
[12:39:23] [Server thread/ERROR]: [BentoBox] isGithubDownloadData
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:23] [Server thread/ERROR]: [BentoBox] Default setting value will be used: 120
[12:39:23] [Server thread/ERROR]: [BentoBox] setGithubConnectionInterval
[12:39:23] [Server thread/ERROR]: [BentoBox] getGithubConnectionInterval
[12:39:23] [Server thread/ERROR]: [BentoBox] world.bentobox.bentobox.Settings@45ece0d2
[12:39:26] [Server thread/ERROR]: [BentoBox] Could not load config object! null
[12:39:26] [Server thread/ERROR]: [BentoBox] java.lang.reflect.InvocationTargetException
[12:39:26] [Server thread/ERROR]: [BentoBox] [BSkyBlock] BSkyBlock settings could not load! Addon disabled.
[12:39:26] [Server thread/ERROR]: [BentoBox] Skipping BSkyBlock due to an unhandled exception...
[12:39:26] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException: Cannot invoke "world.bentobox.bskyblock.Settings.isUseOwnGenerator()" because "this.settings" is null
```

**Comment by tastybento** [comment]
Yes, sorry. It was debug reporting as errors. I'll remove it.

**Comment by SlimeDog** [comment]
Thanks.
